.PHONY: clean All

All:
	@echo "----------Building project:[ MyDebug - Debug ]----------"
	@cd "MyDebug" && "$(MAKE)" -f  "MyDebug.mk"
clean:
	@echo "----------Cleaning project:[ MyDebug - Debug ]----------"
	@cd "MyDebug" && "$(MAKE)" -f  "MyDebug.mk" clean
